name: CI - Testes BikeMap API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: 📦 Instalar dependências
        run: npm install

      - name: ✅ Rodar testes
        run: npm test
